
const GET_DEPARTMENTS_REQUEST = 'GET_DEPARTMENTS_REQUEST'
const GET_DEPARTMENTS_SUCCESS = 'GET_DEPARTMENTS_SUCCESS'
const GET_DEPARTMENTS_FAILURE = 'GET_DEPARTMENTS_FAILURE'

const UPDATE_DEPARTMENTS_REQUEST = 'UPDATE_DEPARTMENTS_REQUEST'
const UPDATE_DEPARTMENTS_SUCCESS = 'UPDATE_DEPARTMENTS_SUCCESS'
const UPDATE_DEPARTMENTS_FAILURE = 'UPDATE_DEPARTMENTS_FAILURE'

const ADD_DEPARTMENTS_REQUEST = 'ADD_DEPARTMENTS_REQUEST'
const ADD_DEPARTMENTS_SUCCESS = 'ADD_DEPARTMENTS_SUCCESS'
const ADD_DEPARTMENTS_FAILURE = 'ADD_DEPARTMENTS_FAILURE'

const GET_EMPLOYEES_REQUEST = 'GET_EMPLOYEES_REQUEST'
const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS'
const GET_EMPLOYEES_FAILURE = 'GET_EMPLOYEES_FAILURE'

const UPDATE_EMPLOYEES_REQUEST = 'UPDATE_EMPLOYEES_REQUEST'
const UPDATE_EMPLOYEES_SUCCESS = 'UPDATE_EMPLOYEES_SUCCESS'
const UPDATE_EMPLOYEES_FAILURE = 'UPDATE_EMPLOYEES_FAILURE'

const ADD_EMPLOYEES_REQUEST = 'ADD_EMPLOYEES_REQUEST'
const ADD_EMPLOYEES_SUCCESS = 'ADD_EMPLOYEES_SUCCESS'
const ADD_EMPLOYEES_FAILURE = 'ADD_EMPLOYEES_FAILURE'

export default {
  GET_DEPARTMENTS_REQUEST,
  GET_DEPARTMENTS_SUCCESS,
  GET_DEPARTMENTS_FAILURE,
  UPDATE_DEPARTMENTS_REQUEST,
  UPDATE_DEPARTMENTS_SUCCESS,
  UPDATE_DEPARTMENTS_FAILURE,
  ADD_DEPARTMENTS_REQUEST,
  ADD_DEPARTMENTS_SUCCESS,
  ADD_DEPARTMENTS_FAILURE,
  GET_EMPLOYEES_REQUEST,
  GET_EMPLOYEES_SUCCESS,
  GET_EMPLOYEES_FAILURE,
  UPDATE_EMPLOYEES_REQUEST,
  UPDATE_EMPLOYEES_SUCCESS,
  UPDATE_EMPLOYEES_FAILURE,
  ADD_EMPLOYEES_REQUEST,
  ADD_EMPLOYEES_SUCCESS,
  ADD_EMPLOYEES_FAILURE
}
